FROM centos:7

USER root

# 安装node.js
RUN yum install -y gcc gcc++ gcc-c++ wget make git libgcc libstdc++ && \
cd / && \
mkdir nodejs_install && \
cd /nodejs_install && \
wget --no-check-certificate https://nodejs.org/dist/v8.11.0/node-v8.11.0.tar.gz && \
tar zxvf node-v8.11.0.tar.gz && \
cd node-v8.11.0 && \
./configure && \
make -j4 && make install && \
node -v && npm -v && \
cd / && \
rm -rf nodejs_install && \
node -v && npm -v

# useing
# docker build -f Dockerfile-nodejs -t centos:node-v8.11.0 .
