FROM node:latest

WORKDIR /blog

RUN node -v && npm -v && \
npm install -g npm && \
npm install -g hexo-cli && \
hexo -v && \
hexo init && \
cp _config.yml _config.yml.bak

# useing
# docker build -f Dockerfile-hexo-v1 -t hexo:v1 .
# 