FROM node:latest

WORKDIR /blog

RUN node -v && npm -v && \
npm install -g npm && \
npm install -g hexo-cli && \
hexo -v && \
hexo init && \

# useing
# docker build -f Dockerfile-hexo -t hexo:v1 .
# 