FROM hexo:v1

RUN git clone https://github.com/theme-next/hexo-theme-next themes/next && \
git clone https://github.com/gaosiqiang/blog_source.git && \
cd ./blog_source && \
cp _config.yml ../

# CMD ["/bin/bash", "/blog/blog_source/deployment_git_blog_source.sh"]

# useing
# docker build -f Dockerfile-gaosiqiang-blog-generate-v2 -t blog-generate:v2 .
# 