FROM node:latest

RUN node -v && npm -v && \
npm install -g npm && \
npm install -g hexo-cli && \
hexo -v && \
cd / && mkdir blog && cd /blog && \
hexo init && ls && \
git clone https://github.com/theme-next/hexo-theme-next themes/next && \
git clone https://github.com/gaosiqiang/blog_source.git && \
cd ./blog_source && \
git config pull.rebase false && git config pull.rebase true && git config pull.ff only && \
mv ../_config.yml ../_config.yml.bak && cp _config.yml ../

# 设置工作目录
WORKDIR /blog/blog_source

CMD ["/bin/bash", "/blog/blog_source/deployment_git_blog_source.sh"]

# useing
# docker build -f Dockerfile-gaosiqiang-blog-generate -t blog-generate:v1 .

# PS
# 查看包的所有版本 npm view hexo-cli versions
# 直接安装最新版 npm install -g hexo-cli
# 安装指定版本 npm install -g hexo-cli@4.2.0

# 参考
# https://zhuanlan.zhihu.com/p/549089297
# https://hexo.io/zh-cn/docs/setup
# https://nodejs.org/zh-cn/download/
# https://nodejs.org/dist/
