FROM hexo:v1

RUN cd /blog && mkdir public && \
git clone https://github.com/theme-next/hexo-theme-next themes/next && \
git clone https://github.com/gaosiqiang/blog_source.git && \
cd ./blog_source && \
git config pull.rebase false && git config pull.rebase true && git config pull.ff only && \
cp _config.yml ../_config.yml

# CMD ["/bin/bash", "/blog/blog_source/deployment_git_blog_source.sh"]
CMD /blog/blog_source/deployment_git_blog_source.sh >> /blog/public/runtime.txt

# useing
# docker build -f Dockerfile-gaosiqiang-blog-generate-v1 -t blog-generate:v1 .
# 先构建hexo:v1镜像
# 