FROM centos:7

# COPY ./Anaconda3-5.1.0-Linux-x86_64.sh /tmp

RUN yum -y install wget bzip2 && \
wget --no-check-certificate https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
# 用脚本安装anaconda需要输入五个个交互式答案顺序分别是Enter，yes，Enter，yes
sh -c '/bin/echo -e "\nyes\n\nyes\n" | bash Miniconda3-latest-Linux-x86_64.sh' && \
# 环境变量生效
source ~/.bashrc && \
rm -f Miniconda3-latest-Linux-x86_64.sh && \
conda info


# Dockerfile-jupyter使用
# cd到Dockerfile-jupyter所在的目录
# docker build -f Dockerfile-jupyter -t jupyter:mini-v1 .
# 
# \n
# yes
# \n
# yes